### ISSUE TITLE
[GENERAL] Code formatting

### ISSUE THREAD

**Issue by matteobaccan** [ministero-salute/it-dgc-gateway-client#16]
Hi

I have seen that the source code of the project has a different code formatting.
In general, this is not a problem but, let me show you this source code

src\main\java\it\interop\dgc\gateway\akamai\AkamaiFastPurge.java

Inside this source code, some lines are ended with 0x0a 

0000000000: 2F 2A **0A** 20 2A 20 20 43 │ 6F 70 79 72 69 67 68 74  /*◙ *  Copyright
0000000010: 20 28 43 29 20 32 30 32 │ 31 20 4D 69 6E 69 73 74   (C) 2021 Minist

and some others with 0x0d 0x0a

0000000390: 69 6D 70 6F 72 74 20 6A │ 61 76 61 2E 6E 65 74 2E  import java.net.
00000003A0: 55 52 49 3B **0D 0A** 69 6D │ 70 6F 72 74 20 6A 61 76  URI;♪◙import jav

Some ide reformats the code using the same line terminator. This kind of end of line mismatch may generate a diff that includes, not only the lines modified, but also all the lines that are committed with a different end of line.

I think maybe a good practice to reformat all the source code of the project to reduce the diff mismatch that may be generated by different IDE or editors.

all the best
matteo baccan

**Comment by astagi** [comment]
Hi @matteobaccan thanks for reporting this! In order to keep source code well formatted I added [Prettier](https://prettier.io/) to this repository and I'm working to add it to the other repository as well.
