### ISSUE TITLE
[GENERAL] How to get certificates to decode codes yourself

### ISSUE THREAD

**Issue by ybrodsky** [ministero-salute/it-dgc-gateway-client#20]
Hello,
I know this is probably not the right place to ask but I can't find this anywhere.
I am required to read QR codes and validate that the code is valid and the person is "ok".

As I understand I need some certificates to validate the data is correct, but I can't find how or from where get these certificates.

Any help would be appreciated.

**Comment by lcfr-dev** [comment]
Hi,
I was in the same situation few days ago. [https://github.com/eu-digital-green-certificates/dgc-overview](This link) can may be help you. You are asking about how get certificates, but in this case you don'have. All the verification can be done offline, the only thing you need is list of valid identifier ([https://eu-digital-green-certificates.github.io/dgc-gateway/#/](look here).

**Comment by lcfr-dev** [comment]
Hi,
I was in the same situation few days ago. [https://github.com/eu-digital-green-certificates/dgc-overview](This link) can may be help you. You are asking about how get certificates, but in this case you don'have. All the verification can be done offline, the only thing you need is list of valid identifier. You can get more information [here](https://dgca-verifier-service-eu-acc.cfapps.eu10.hana.ondemand.com/context)

**Comment by lcfr-dev** [comment]
Hi,
I was in the same situation few days ago. [This link](https://github.com/eu-digital-green-certificates/dgc-overview) can may be help you. You are asking about how get certificates, but in this case you don'have to. All the verification can be done offline, the only thing you need is list of valid identifier. You can get more information [here](https://dgca-verifier-service-eu-acc.cfapps.eu10.hana.ondemand.com/context).  [Here](https://ec.europa.eu/health/ehealth/covid-19_en) you can get all specs and document avaliable

**Comment by astagi** [comment]
Hi @ybrodsky @lcfr-dev we've just released [DCC Utils library](https://github.com/ministero-salute/dcc-utils/actions).

In the example section you can find [a script](https://github.com/ministero-salute/dcc-utils/blob/master/examples/verify_signature_from_list.js) that uses AT trust list. Hope it helps!
