### ISSUE TITLE
Process to get authorized to access National backEnd

### ISSUE THREAD

**Issue by davide-cecchetto-prodos** [ministero-salute/it-dgc-gateway-client#21]
Hi, we want to build a totem to verify the validity of Green Pass in Italy. I have read lot of technical documentation, but I can't find any reference to the process to get authorized to access the service. Someone can give us some hints?

Thank you.

**Comment by astagi** [comment]
Hi @davide-cecchetto-prodos I'm going to ask the team for the public access to the national backend, in the mean time you can give a glance at [DCC Utils library](https://github.com/ministero-salute/dcc-utils/actions). In the example section you can find [a script](https://github.com/ministero-salute/dcc-utils/blob/master/examples/verify_signature_from_list.js) that uses AT trust list containing all the keys from EU member states. We're also defining and working on Italy's business rules. 

Hope it helps!

**Comment by astagi** [comment]
@davide-cecchetto-prodos if you need more support, better move this discussion inside the [DCC Utils repository](https://github.com/ministero-salute/dcc-utils/) cause your question has topics strictly related to certificate validation. In that repo you can find examples, code and open discussion that may clarify your doubts.
